sudo: required
services:
  - docker

before_install:
  - docker build -t keshaldesai/docker-react -f Dockerfile.dev .

script:
  - docker run keshaldesai/docker-react npm run test -- --coverage
